Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [4]:
import pandas as pd
import numpy as np
data=pd.read_csv('Patient_Data.csv')
data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes

In [6]:
data_selected=data[['PatientID','Department','Doctor','BillAmount']]
print(data_selected)

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [8]:
data=data.drop(['ReceptionistID','CheckInTime'],axis=1)
data

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [10]:
data_1=data.groupby('Department').sum('BillAmount')
data_1

             PatientID  BillAmount
Department
Cardiology         306     16200.0
Dermatology        105         0.0
Neurology          102         0.0
Orthopedics        103      7500.0

In [11]:
data_2=data.groupby('Department').agg({'BillAmount': 'sum'})
data_2

             BillAmount
Department
Cardiology      16200.0
Dermatology         0.0
Neurology           0.0
Orthopedics      7500.0

In [12]:
d=d.drop_duplicates('PatientID')
d

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [13]:
d=d.drop_duplicates('PatientID')
d

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [14]:
d=d.fillna(data.BillAmount.mean())
d

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5925.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5925.0

In [22]:
data_b=pd.read_csv('Billing_Data (1).csv')
data_b

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [23]:
d2=d.merge(data_b,on='PatientID')
d2

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,1000,4000

In [24]:
new_data={'PatientID':[106,107],'Name':['Tamil','Ravi'],'Department':['Neurology','Dermatolgy'],'Doctor':['Dr.Suji','Dr.Preethi'],'BillAmount':[1200,1500]}
new_data

{'PatientID': [106, 107],
 'Name': ['Tamil', 'Ravi'],
 'Department': ['Neurology', 'Dermatolgy'],
 'Doctor': ['Dr.Suji', 'Dr.Preethi'],
 'BillAmount': [1200, 1500]}

In [25]:
new=pd.concat([d,pd.DataFrame(new_data)],ignore_index=True)
new

   PatientID     Name   Department      Doctor  BillAmount
0        101    Alice   Cardiology   Dr. Smith      5000.0
1        102      Bob    Neurology    Dr. John      5925.0
2        103  Charlie  Orthopedics     Dr. Lee      7500.0
3        104    David   Cardiology   Dr. Smith      6200.0
4        105      Eva  Dermatology    Dr. Rose      5925.0
5        106    Tamil    Neurology     Dr.Suji      1200.0
6        107     Ravi   Dermatolgy  Dr.Preethi      1500.0

In [26]:
dd={'InsuranceCovered':[1000,1500,2000,2500,3000,3500,400],'FinalAmount':[4000,3500,4000,5500,6000,2500,3500]}
dd

{'InsuranceCovered': [1000, 1500, 2000, 2500, 3000, 3500, 400],
 'FinalAmount': [4000, 3500, 4000, 5500, 6000, 2500, 3500]}

In [27]:
new_data=pd.concat([new,pd.DataFrame(dd)],axis=1)
new_data

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1000,4000
1,102,Bob,Neurology,Dr. John,5925.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2000,4000
3,104,David,Cardiology,Dr. Smith,6200.0,2500,5500
4,105,Eva,Dermatology,Dr. Rose,5925.0,3000,6000
5,106,Tamil,Neurology,Dr.Suji,1200.0,3500,2500
6,107,Ravi,Dermatolgy,Dr.Preethi,1500.0,400,3500